"""
Django settings for plantedgews project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
from django.conf import settings
import datetime


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z6qf3khupwgxeb^3a!+9g!3d+%jm6!&(k7&c4-u%=51k4hm%xa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_crontab',
    'rest_framework',
    'rangefilter',
    'easy_select2',
    'smart_selects',

    # 'storages',

    'simple_history',
    'plantedge',
    'debug_panel',
    'downloads3'


]
CRONJOBS = [

    # this will run “At 23:59.”  daily
    ('59 23 * * *', "plantedge.facade.vegetationIndex.check_update_asset_cron"),
    # this will run “At 16:59.”  daily
    ('59 16 * * *', "plantedge.facade.analysis.start_analysis_cron"),
    #Email sending  will run    At 10:05 on every Monday
    ('5 10 * * 1', "plantedge.facade.weeklyEmailCron.send_email_cron")


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_panel.middleware.DebugPanelMiddleware',

]

ROOT_URLCONF = 'plantedgews.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plantedgews.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

CELERYD_TASK_SOFT_TIME_LIMIT = 60

# REDIS related settings
REDIS_HOST = 'localhost'
REDIS_PORT = '6379'
BROKER_URL = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'
BROKER_TRANSPORT_OPTIONS = {'visibility_timeout': 43200}
CELERY_RESULT_BACKEND = 'redis://' + REDIS_HOST + ':' + REDIS_PORT + '/0'

# KEYS
# TODO: MOVE AS ENVIRONMENT VARIABLE LATER
# PLANET_API_KEY = '710504db403e4f1ea91eb9db55d585c7'
# PLANET_API_KEY = '3f0323dabe764793ba50a57f39e9a683'
# PLANET_API_KEY = 'e1b55070d4dd4c0286595d5f19b87c2e'
# PLANET_API_KEY = '870a3ff491af4cd0afe4fe72b26e8025'
# PLANET_API_KEY = 'c8c5df14804c4c5baec632a0d51ceb03'
# PLANET_API_KEY = '45678e45736e4679948da44aca552121'
PLANET_API_KEY = '58a22d9370944c899a34a84c50254c1c'
CAS_URL        = 'https://api.planet.com/compute/ops/clips/v1/'

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Etc/GMT-7'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
LOCAL_ASSETS_DIR = 'storage'
WEED_ALERT_DIR = './polygonized_weed_alert_json/'


# Amazon S3 client configurations
AWS_ACCESS_KEY_ID       = 'AKIAJGIY4A62J4LIBBVA'
AWS_STORAGE_BUCKET_NAME = 'oc-dev-geosense'
AWS_SECRET_ACCESS_KEY   = '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'

try:
    from plantedgews.local_settings import *
except:
    pass


from .email_setting import *
EMAIL_USE_TLS = EMAIL_USE_TLS
EMAIL_HOST = EMAIL_HOST
EMAIL_HOST_USER =  EMAIL_HOST_USER
EMAIL_PORT = EMAIL_PORT
EMAIL_HOST_PASSWORD = EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = DEFAULT_FROM_EMAIL


# JQUERY_URL = True
USE_DJANGO_JQUERY = True
# SELECT2_JS  = 'easy_select2/vendor/select2/select2.min.js'
# SELECT2_CSS = 'easy_select2/vendor/select2/select2.min.css'
# SELECT2_USE_BUNDLED_JQUERY  = True