# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-30 08:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
                ('directory', models.CharField(blank=True, max_length=200, null=True)),
                ('alert_geosjon', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aoi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_aoi_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('raw_coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None), size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('variant', models.TextField(blank=True, null=True)),
                ('date_planted', models.DateField(default='2017-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('storage_url', models.CharField(blank=True, max_length=200, null=True)),
                ('planet_item_id', models.CharField(max_length=20)),
                ('usability_score', models.FloatField(default=1.1)),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Aoi')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Aoi')),
            ],
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_plot_ID', models.CharField(blank=True, max_length=50, null=True)),
                ('client_plot_description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('A', 'Active'), ('D', 'Disable')], default='A', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('weed_enable', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1)),
                ('forest_health_enable', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1)),
                ('variant', models.CharField(choices=[('Epel', 'Epel'), ('Acra', 'Acra')], default='Epel', max_length=4)),
                ('date_planted', models.DateField(default='2017-01-01')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationStat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_record', models.CharField(blank=True, max_length=100, null=True)),
                ('plot_id', models.IntegerField()),
                ('plot_id_consol', models.IntegerField()),
                ('date', models.DateField()),
                ('variant', models.CharField(blank=True, max_length=30, null=True)),
                ('planted_date', models.DateField()),
                ('age_at_obs_months', models.IntegerField(blank=True, null=True)),
                ('min_rgb_haze_indicator', models.FloatField(blank=True, null=True)),
                ('likely_haze', models.IntegerField(default=0)),
                ('min_rgb_bad_fraction', models.FloatField(blank=True, null=True)),
                ('likely_cloud', models.IntegerField(default=0)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('ndvi_95', models.FloatField(blank=True, null=True)),
                ('ndvi_80', models.FloatField(blank=True, null=True)),
                ('ndvi_std', models.FloatField(blank=True, null=True)),
                ('ndvi_count', models.FloatField(default=0)),
                ('gndvi', models.FloatField(blank=True, null=True)),
                ('gndvi_95', models.FloatField(blank=True, null=True)),
                ('gndvi_80', models.FloatField(blank=True, null=True)),
                ('gndvi_std', models.FloatField(blank=True, null=True)),
                ('gndvi_count', models.IntegerField(default=0)),
                ('evi', models.FloatField(blank=True, null=True)),
                ('evi_95', models.FloatField(blank=True, null=True)),
                ('evi_80', models.FloatField(blank=True, null=True)),
                ('evi_std', models.FloatField(blank=True, null=True)),
                ('evi_count', models.IntegerField(default=0)),
                ('rvi', models.FloatField(blank=True, null=True)),
                ('rvi_95', models.FloatField(blank=True, null=True)),
                ('rvi_80', models.FloatField(blank=True, null=True)),
                ('rvi_std', models.FloatField(blank=True, null=True)),
                ('rvi_count', models.IntegerField(default=0)),
                ('dirt', models.FloatField(blank=True, null=True)),
                ('dirt_95', models.FloatField(blank=True, null=True)),
                ('dirt_std', models.FloatField(blank=True, null=True)),
                ('dirt_count', models.IntegerField(default=0)),
                ('ndwi', models.FloatField(blank=True, null=True)),
                ('ndwi_95', models.FloatField(blank=True, null=True)),
                ('ndwi_80', models.FloatField(blank=True, null=True)),
                ('ndwi_20', models.FloatField(blank=True, null=True)),
                ('ndwi_05', models.FloatField(blank=True, null=True)),
                ('ndwi_std', models.FloatField(blank=True, null=True)),
                ('ndwi_count', models.IntegerField(default=0)),
                ('ndwi_high_count', models.IntegerField(default=0)),
                ('asset_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('plot_alert_json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Thresholds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_generated', models.DateField()),
                ('quantile_df', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='aoi',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Client'),
        ),
        migrations.AddField(
            model_name='aoi',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Plots'),
        ),
    ]
