# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-31 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='plot',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, to='plantedge.Plots'),
            preserve_default=False,
        ),
    ]
