# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-01 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0002_subscriber_plot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='plot',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='plot',
            field=models.ManyToManyField(to='plantedge.Plots'),
        ),
    ]
