# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-01 16:00
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0003_auto_20181101_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='plot',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='plot',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='client', chained_model_field='client', default=53, on_delete=django.db.models.deletion.CASCADE, to='plantedge.Plots'),
            preserve_default=False,
        ),
    ]
