# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-01 16:55
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0004_auto_20181101_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='plot',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='plot',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='client', chained_model_field='client', to='plantedge.Plots'),
        ),
    ]
