# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-11-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0005_auto_20181101_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='creation_date',
            new_name='alert_date',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='alert_geosjon',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='directory',
        ),
        migrations.AddField(
            model_name='alert',
            name='file_path',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='plot',
            field=models.ForeignKey(default=53, on_delete=django.db.models.deletion.CASCADE, to='plantedge.Plots'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Verified', 'Verified'), ('False_alarm', 'False_alarm')], default='Active', max_length=12),
        ),
        migrations.AddField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('Weed', 'Weed'), ('Forest_health', 'Forest_health')], default='Weed', max_length=14),
        ),
    ]
