# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-22 08:09
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aoi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_aoi_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('storage_url', models.CharField(max_length=50)),
                ('planet_asset_id', models.CharField(max_length=20)),
                ('note', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Aoi')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Aoi')),
            ],
        ),
        migrations.AddField(
            model_name='aoi',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Client'),
        ),
    ]
