# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-24 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='planet_asset_id',
            new_name='planet_item_id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='storage_url',
            field=models.CharField(max_length=200),
        ),
    ]
