# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-25 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0002_auto_20180124_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='usability_score',
            field=models.FloatField(default=1.1),
        ),
    ]
