# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-03 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0006_auto_20180816_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_plot_ID', models.TextField(blank=True, null=True)),
                ('client_plot_description', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weed_enable', models.BooleanField(default=False)),
                ('forest_health_enable', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantedge.Client')),
            ],
        ),
        migrations.AddField(
            model_name='aoi',
            name='date_planted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aoi',
            name='variant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='coordinates',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='raw_coordinates',
            field=models.TextField(),
        ),
    ]
