# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0007_auto_20180903_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plots',
            name='client_plot_ID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plots',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plots',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
