# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0013_auto_20180904_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='plot_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='plantedge.Plots'),
            preserve_default=False,
        ),
    ]
