# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-04 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantedge', '0014_aoi_plot_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aoi',
            old_name='plot_id',
            new_name='plot',
        ),
    ]
